//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Publisher failed to execute..
        /// </summary>
        internal static string RES_CUSTOM_PUBLISHER_FAILURE_MESSAGE {
            get {
                return ResourceManager.GetString("RES_CUSTOM_PUBLISHER_FAILURE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event source {0} does not exist and cannot be created with the current permissions..
        /// </summary>
        internal static string RES_DEFAULTPUBLISHER_EVENTLOG_DENIED {
            get {
                return ResourceManager.GetString("RES_DEFAULTPUBLISHER_EVENTLOG_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading exceptionManagement configuration..
        /// </summary>
        internal static string RES_EXCEPTION_LOADING_CONFIGURATION {
            get {
                return ResourceManager.GetString("RES_EXCEPTION_LOADING_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information could not be accessed..
        /// </summary>
        internal static string RES_EXCEPTIONMANAGEMENT_INFOACCESS_EXCEPTION {
            get {
                return ResourceManager.GetString("RES_EXCEPTIONMANAGEMENT_INFOACCESS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string RES_EXCEPTIONMANAGEMENT_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("RES_EXCEPTIONMANAGEMENT_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Manager could not serialize the Exception information into XML..
        /// </summary>
        internal static string RES_EXCEPTIONMANAGEMENT_XMLSERIALIZATION_EXCEPTION {
            get {
                return ResourceManager.GetString("RES_EXCEPTIONMANAGEMENT_XMLSERIALIZATION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionManagerInternalException.
        /// </summary>
        internal static string RES_EXCEPTIONMANAGER_INTERNAL_EXCEPTIONS {
            get {
                return ResourceManager.GetString("RES_EXCEPTIONMANAGER_INTERNAL_EXCEPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionManagerPublishedException.
        /// </summary>
        internal static string RES_EXCEPTIONMANAGER_PUBLISHED_EXCEPTIONS {
            get {
                return ResourceManager.GetString("RES_EXCEPTIONMANAGER_PUBLISHED_EXCEPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdditionalInformationProperty.
        /// </summary>
        internal static string RES_XML_ADDITIONAL_INFORMATION {
            get {
                return ResourceManager.GetString("RES_XML_ADDITIONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string RES_XML_EXCEPTION {
            get {
                return ResourceManager.GetString("RES_XML_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionInformation.
        /// </summary>
        internal static string RES_XML_ROOT {
            get {
                return ResourceManager.GetString("RES_XML_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace.
        /// </summary>
        internal static string RES_XML_STACK_TRACE {
            get {
                return ResourceManager.GetString("RES_XML_STACK_TRACE", resourceCulture);
            }
        }
    }
}
